name: CI tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request_target:
    branches:
      - master
      - main

jobs:
  lint:
    uses: ./.github/workflows/pylint.yaml

  build:
    uses: ./.github/workflows/builders.yaml
