name: Image Push
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
      tags: ${{ steps.build.outputs.tags }}
    steps:
      - uses: actions/checkout@v2

      - name: Decide Image Name
        id: set-image
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "release" && "${GITHUB_EVENT_ACTION}" == "published" ]]; then
            echo "image=bugzooka" >> $GITHUB_OUTPUT
          else
            echo "image=bugzooka-dev" >> $GITHUB_OUTPUT
          fi

      - name: Build BugZooka Image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ steps.set-image.outputs.image }}
          context: .
          tags: latest
          containerfiles: |
            ./Dockerfile

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push BugZooka Image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ needs.build.outputs.image }}
          tags: ${{ needs.build.outputs.tags }}
          registry: quay.io/redhat-performance
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
